"""Add remarks to resume match

Revision ID: 29516860d42f
Revises: e7c0d47da71d
Create Date: 2025-05-09 22:32:14.127182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29516860d42f'
down_revision: Union[str, None] = 'e7c0d47da71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumematch', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumematch', 'remarks')
    # ### end Alembic commands ###
