"""make optional fields nullable

Revision ID: 2fce439a40da
Revises: a49aa4d55eb2
Create Date: 2025-05-04 14:39:19.969336

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2fce439a40da'
down_revision: Union[str, None] = 'a49aa4d55eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobapplication', 'resume_file_path',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('jobapplication', 'job_description_file_path',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobapplication', 'job_description_file_path',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('jobapplication', 'resume_file_path',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
