"""update job-tracker-table application-date field

Revision ID: a49aa4d55eb2
Revises: 5761b1b475c3
Create Date: 2025-05-04 14:29:58.610697

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a49aa4d55eb2'
down_revision: Union[str, None] = '5761b1b475c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('application_date', sa.DateTime(), nullable=True))
    op.drop_column('jobapplication', 'applied_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication',
                  sa.Column('applied_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('jobapplication', 'application_date')
    # ### end Alembic commands ###
